package indigoplugin.generators

import indigoplugin.IndigoGenerators

object EmbedText {

  def generate(
      moduleName: String,
      fullyQualifiedPackage: String,
      filePath: os.Path
  ): IndigoGenerators.SourceParams => Seq[os.Path] = params => {

    val text =
      if (!os.exists(filePath)) throw new Exception("Text file to embed not found: " + filePath.toString())
      else {
        os.read(filePath)
      }

    val wd = params.destination / Generators.OutputDirName

    os.makeDir.all(wd)

    val file = wd / s"$moduleName.scala"

    val contents =
      s"""package $fullyQualifiedPackage
      |
      |// DO NOT EDIT: Generated by Indigo.
      |object $moduleName:
      |
      |  val text: String =
      |    ${Generators.TripleQuotes}$text${Generators.TripleQuotes}
      |""".stripMargin

    os.write.over(file, contents)

    Seq(file)
  }

  def generate(
      moduleName: String,
      fullyQualifiedPackage: String,
      filePath: os.Path,
      present: String => String
  ): IndigoGenerators.SourceParams => Seq[os.Path] = params => {

    val text =
      if (!os.exists(filePath)) throw new Exception("Text file to embed not found: " + filePath.toString())
      else {
        os.read(filePath)
      }

    val wd = params.destination / Generators.OutputDirName

    os.makeDir.all(wd)

    val file = wd / s"$moduleName.scala"

    val contents =
      s"""package $fullyQualifiedPackage
      |
      |// DO NOT EDIT: Generated by Indigo.
      |
      |${present(text)}
      |""".stripMargin

    os.write.over(file, contents)

    Seq(file)
  }

}
