package indigoplugin.generators

import indigoplugin.IndigoGenerators
import indigoplugin.FontOptions
import indigoplugin.FontLayout
import indigoplugin.CharSet
import indigoplugin.RGB
import indigoplugin.utils.Utils

class GeneratorAcceptanceTests extends munit.FunSuite {

  val workspaceDir = Utils.findWorkspace

  val sourceCSV              = workspaceDir / "test-assets" / "data" / "stats.csv"
  val sourceMD               = workspaceDir / "test-assets" / "data" / "stats.md"
  val sourceColours          = workspaceDir / "test-assets" / "data" / "colours.txt"
  val sourceFontTTF          = workspaceDir / "test-files" / "VCR_OSD_MONO_1.001.ttf"
  val sourceFontTTFPixelated = workspaceDir / "test-files" / "pixelated.ttf"

  val targetDir = workspaceDir / "out" / "indigo-plugin-generator-acceptance-test-output"

  private def cleanUp(): Unit = {
    if (os.exists(targetDir)) {
      os.remove.all(target = targetDir)
    }

    os.makeDir.all(targetDir)
  }

  override def beforeAll(): Unit                     = cleanUp()
  override def beforeEach(context: BeforeEach): Unit = cleanUp()

  test("Can generate font bitmap and FontInfo from TTF file - normal layout") {

    val imageOutDir = targetDir / Generators.OutputDirName / "images"
    os.makeDir.all(imageOutDir)

    val options: FontOptions =
      FontOptions("my font normal", 16, CharSet.ASCII)
        .withColor(RGB.Green)
        .noAntiAliasing
        // .useAntiAliasing
        .withLayout(FontLayout.Normal(16))

    val files =
      IndigoGenerators("com.example.test")
        .embedFont("MyFontNormal", sourceFontTTFPixelated, options, imageOutDir)
        .toSourcePaths(targetDir)

    files.toList match {
      case fontInfo :: Nil =>
        assert(os.exists(fontInfo))
        assert(os.exists(imageOutDir / "MyFontNormal.png"))

      case _ =>
        fail(
          s"Unexpected number of files generated, got ${files.length} files:\n${files.map(_.toString()).mkString("\n")}"
        )
    }
  }

  test("Can generate font bitmap and FontInfo from TTF file - monospace layout") {

    val imageOutDir = targetDir / Generators.OutputDirName / "images"

    os.makeDir.all(imageOutDir)

    val options: FontOptions =
      FontOptions("my font mono", 16, CharSet.Alphanumeric)
        .withColor(RGB.Green)
        .noAntiAliasing
        .withLayout(FontLayout.monospace(16))

    val files =
      IndigoGenerators("com.example.test")
        .embedFont("MyFontMono", sourceFontTTF, options, imageOutDir)
        .toSourcePaths(targetDir)

    files.toList match {
      case fontInfo :: Nil =>
        assert(os.exists(fontInfo))
        assert(os.exists(imageOutDir / "MyFontMono.png"))

      case _ =>
        fail(
          s"Unexpected number of files generated, got ${files.length} files:\n${files.map(_.toString()).mkString("\n")}"
        )
    }
  }

  test("Can generate font bitmap and FontInfo from TTF file - indexed grid layout") {

    val imageOutDir = targetDir / Generators.OutputDirName / "images"

    os.makeDir.all(imageOutDir)

    val options: FontOptions =
      FontOptions("my font indexed", 16, CharSet.ExtendedASCII)
        .withColor(RGB.White)
        .noAntiAliasing
        .withLayout(FontLayout.indexedGrid(16))

    val files =
      IndigoGenerators("com.example.test")
        .embedFont("MyFontIndexed", sourceFontTTF, options, imageOutDir)
        .toSourcePaths(targetDir)

    files.toList match {
      case fontInfo :: Nil =>
        assert(os.exists(fontInfo))
        assert(os.exists(imageOutDir / "MyFontIndexed.png"))

      case _ =>
        fail(
          s"Unexpected number of files generated, got ${files.length} files:\n${files.map(_.toString()).mkString("\n")}"
        )
    }
  }

  test("Can generate an enum from a CSV file") {

    val files =
      IndigoGenerators("com.example.test").embedCSV
        .asEnum("StatsEnum", sourceCSV)
        .toSourcePaths(targetDir)

    files.headOption match {
      case None =>
        fail("No file was generated")

      case Some(src) =>
        assert(clue(src) == clue(targetDir / "indigo-compile-codegen-output" / "StatsEnum.scala"))

        val actual = os.read(src)

        val expected =
          """
          |package com.example.test
          |
          |// DO NOT EDIT: Generated by Indigo.
          |
          |enum StatsEnum(val level: Int, val bonus: Int, val stackable: Option[Boolean]):
          |  case Intelligence extends StatsEnum(2, 4, Some(true))
          |  case Strength extends StatsEnum(10, 0, None)
          |  case Fortitude extends StatsEnum(4, 1, Some(false))
          |""".stripMargin

        assertEquals(actual.trim, expected.trim)
    }
  }

  test("Can generate a map from a markdown table file") {

    val files =
      IndigoGenerators("com.example.test").embedMarkdownTable
        .asMap("StatsMap", sourceMD)
        .toSourcePaths(targetDir)

    files.headOption match {
      case None =>
        fail("No file was generated")

      case Some(src) =>
        assert(clue(src) == clue(targetDir / "indigo-compile-codegen-output" / "StatsMap.scala"))

        val actual = os.read(src)

        val expected =
          """
          |package com.example.test
          |
          |// DO NOT EDIT: Generated by Indigo.
          |
          |final case class StatsMap(level: Int, bonus: Int, code: Option[String])
          |object StatsMap:
          |  val data: Map[String, StatsMap] =
          |    Map(
          |      "intelligence" -> StatsMap(2, 4, Some("i")),
          |      "strength" -> StatsMap(10, 0, None),
          |      "fortitude" -> StatsMap(4, 1, Some("_frt"))
          |    )
          |""".stripMargin

        assertEquals(actual.trim, expected.trim)
    }
  }

  test("Can generate a map from a markdown table file (armour, unformatted)") {

    val files =
      IndigoGenerators("com.example.test").embedMarkdownTable
        .asEnum("Armour", workspaceDir / "test-assets" / "data" / "armour.md")
        .toSourcePaths(targetDir)

    files.headOption match {
      case None =>
        fail("No file was generated")

      case Some(src) =>
        assert(clue(src) == clue(targetDir / "indigo-compile-codegen-output" / "Armour.scala"))

        val actual = os.read(src)

        val expected =
          """
          |package com.example.test
          |
          |// DO NOT EDIT: Generated by Indigo.
          |
          |enum Armour(val defenseBonus: Int):
          |  case LeatherArmor extends Armour(1)
          |  case ChainMail extends Armour(3)
          |""".stripMargin

        assertEquals(actual.trim, expected.trim)
    }
  }

  test("Can generate a custom output from a markdown table file") {

    val files =
      IndigoGenerators("com.example.test").embedMarkdownTable
        .asCustom("StatsMap", sourceMD) { data =>
          s"""/*
          |${data.map(_.map(cell => s"${cell.asString}: ${cell.giveTypeName}").mkString(",")).mkString("\n")}
          |*/""".stripMargin.trim
        }
        .toSourcePaths(targetDir)

    files.headOption match {
      case None =>
        fail("No file was generated")

      case Some(src) =>
        assert(clue(src) == clue(targetDir / "indigo-compile-codegen-output" / "StatsMap.scala"))

        val actual = os.read(src)

        val expected =
          """
          |package com.example.test
          |
          |// DO NOT EDIT: Generated by Indigo.
          |/*
          |"name": String,"level": String,"bonus": String,"code": String
          |"intelligence": String,2: Int,4: Int,Some("i"): Option[String]
          |"strength": String,10: Int,0: Int,None: Option[Any]
          |"fortitude": String,4: Int,1: Int,Some("_frt"): Option[String]
          |*/
          |""".stripMargin

        assertEquals(actual.trim, expected.trim)
    }
  }

  test("Can generate Aseprite Data") {

    val jsonFile = workspaceDir / "test-assets" / "captain" / "Captain Clown Nose Data.json"

    val files =
      IndigoGenerators("com.example.test")
        .embedAseprite("MyAnimation", jsonFile)
        .toSourcePaths(targetDir)

    files.headOption match {
      case None =>
        fail("No file was generated")

      case Some(src) =>
        assert(clue(src) == clue(targetDir / "indigo-compile-codegen-output" / "MyAnimation.scala"))

        val actual = os.read(src)

        val expected =
          """
          |package com.example.test
          |
          |import indigo.shared.formats.*
          |
          |// DO NOT EDIT: Generated by Indigo.
          |object MyAnimation:
          |
          |  val aseprite: Aseprite =
          |    Aseprite(List(AsepriteFrame("Captain Clown Nose 0.aseprite"
          |""".stripMargin

        assert(clue(actual.trim).startsWith(clue(expected.trim)))
    }

  }

  test("Can embed a txt tile") {

    val files =
      IndigoGenerators("com.example.test")
        .embedText("ColoursText", sourceColours)
        .toSourcePaths(targetDir)

    files.headOption match {
      case None =>
        fail("No file was generated")

      case Some(src) =>
        assert(clue(src) == clue(targetDir / "indigo-compile-codegen-output" / "ColoursText.scala"))

        val actual = os.read(src)

        val expected =
          s"""
          |package com.example.test
          |
          |// DO NOT EDIT: Generated by Indigo.
          |object ColoursText:
          |
          |  val text: String =
          |    ${Generators.TripleQuotes}red
          |green
          |blue
          |${Generators.TripleQuotes}
          |""".stripMargin

        assertEquals(actual.trim, expected.trim)
    }
  }

  test("Can embed a txt tile and transform it") {

    val files =
      IndigoGenerators("com.example.test")
        .embed("ColoursList", sourceColours) { text =>
          "val colours: List[String] = " + text.split("\n").map(t => s"""\"$t\"""").mkString("List(", ", ", ")")
        }
        .toSourcePaths(targetDir)

    files.headOption match {
      case None =>
        fail("No file was generated")

      case Some(src) =>
        assert(clue(src) == clue(targetDir / "indigo-compile-codegen-output" / "ColoursList.scala"))

        val actual = os.read(src)

        val expected =
          """
          |package com.example.test
          |
          |// DO NOT EDIT: Generated by Indigo.
          |
          |val colours: List[String] = List("red", "green", "blue")
          |
          |""".stripMargin

        assertEquals(actual.trim, expected.trim)
    }
  }

}
