baseURL = 'https://indigoengine.io/'
languageCode = 'en-gb'
title = 'Indigo'

contentDir = '../indigo/indigo-docs/target/mdoc/'

staticDir = ['static', '../target/scala-3.2.2/site-docs']

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = "https://github.com/PurpleKingdomGames/indigo/tree/main/indigo/docs"
  # Author of the site, will be used in meta information
  author = "Dave Smith"
  # Description of the site, will be used in meta information
  description = "An FP game engine for Scala"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = true
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # If set to false, a Home button will appear below the search bar on the menu.
  # It is redirecting to the landing page of the current language if specified. (Default is "/")
  disableLandingPageButton = true
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # If set to true, prevents Hugo from including the mermaid module if not needed (will reduce load times and traffic)
  disableMermaid = true
  # Specifies the remote location of the mermaid js
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = true
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "indigo"
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  custom_css = ["css/foo.css", "css/bar.css"]
  # Change the title separator. Default to "::".
  titleSeparator = "-"

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github"
identifier = "github"
url = "https://github.com/PurpleKingdomGames/indigo"
weight = 10
[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Indigo API Docs"
identifier = "apidocs"
url = "/api/"
weight = 20
[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> GitHub Sponsors"
identifier = "sponsors"
url = "https://github.com/sponsors/PurpleKingdomGames"
weight = 30
