addSbtPlugin("org.scala-js"             %% "sbt-scalajs"  % "1.3.1")
addSbtPlugin("io.indigoengine"          %% "sbt-indigo"   % SbtIndigoVersion.getVersion)
addSbtPlugin("com.eed3si9n"             %% "sbt-assembly" % "0.14.10")
addSbtPlugin("org.xerial.sbt"           %% "sbt-sonatype" % "3.9.2")
addSbtPlugin("com.jsuereth"             %% "sbt-pgp"      % "2.0.1")
addSbtPlugin("ch.epfl.lamp"              % "sbt-dotty"    % "0.5.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.16")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix" % "0.9.24")
