addSbtPlugin("org.scala-js"             %% "sbt-scalajs"  % "1.6.0")
addSbtPlugin("io.indigoengine"          %% "sbt-indigo"   % SbtIndigoVersion.getVersion)
addSbtPlugin("org.xerial.sbt"           %% "sbt-sonatype" % "3.9.7")
addSbtPlugin("com.jsuereth"             %% "sbt-pgp"      % "2.0.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.17")
