object ExampleProjects {
  val exampleProjects: List[String] =
    List(
      "assetLoading",
      "audio",
      "automata",
      "basicSetup",
      "blending",
      "button",
      "confetti",
      "distortion",
      "effects",
      "errors",
      "fireworks",
      "graphic",
      "group",
      "http",
      "inputfield",
      "inputmapper",
      "mouseevents",
      "jobs",
      "lighting",
      "radio",
      "scenesSetup",
      "sprite",
      "subSystems",
      "text",
      "tiled",
      "websocket"
    )
}
