name: CI
on: [workflow_dispatch, push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        java-version: adopt@1.11
    - uses: sbt/setup-sbt@v1
    - name: Indigo Compile & Test
      run: bash build.sh
